### PR TITLE
Update to be compatible with React 15.3

### PR DESCRIPTION
**Pull request by fvzzy**

### CODE REVIEW

**Comment by rnsloan** [comment]
👍

**Comment by fvzzy** [comment]
@hadimichael could you please publish a new npm release when you get a chance?

**Comment by hdmchl** [comment]
FYI - would've been nicer if we'd solved this without lodash. I'd really like to remove lodash as a dependency of this lib.

Anyway, updated (1.0.2) now on NPM: https://www.npmjs.com/package/react-document-modifier

**Comment by fvzzy** [comment]
Noted - will push another update removing lodash usages in here when I get a chance. Cheers.

**Pull request merged**
